name: Release
on:
  push:
    tags:
       - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: "Push (branch: major version)"
      run: git push -f origin "HEAD:refs/heads/$(echo "${GITHUB_REF#refs/tags/}" | cut -d '.' -f1)"
